// <auto-generated />
using System;
using KnjiznicaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnjiznicaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911151229_Intial")]
    partial class Intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnjigeZanrovi", b =>
                {
                    b.Property<int>("KnjigeId")
                        .HasColumnType("int");

                    b.Property<int>("ZanroviId")
                        .HasColumnType("int");

                    b.HasKey("KnjigeId", "ZanroviId");

                    b.HasIndex("ZanroviId");

                    b.ToTable("KnjigeZanrovi");
                });

            modelBuilder.Entity("KnjiznicaAPI.Models.AutorKnjige", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("godinaRodenja")
                        .HasColumnType("int");

                    b.Property<string>("imeAutora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AutoriKnjiga");
                });

            modelBuilder.Entity("KnjiznicaAPI.Models.Knjige", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorKnjigeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("datumUnosa")
                        .HasColumnType("datetime2");

                    b.Property<string>("nazivKnjige")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorKnjigeId");

                    b.ToTable("Knjige");
                });

            modelBuilder.Entity("KnjiznicaAPI.Models.Zanrovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("imeZanra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");
                });

            modelBuilder.Entity("KnjigeZanrovi", b =>
                {
                    b.HasOne("KnjiznicaAPI.Models.Knjige", null)
                        .WithMany()
                        .HasForeignKey("KnjigeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnjiznicaAPI.Models.Zanrovi", null)
                        .WithMany()
                        .HasForeignKey("ZanroviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnjiznicaAPI.Models.Knjige", b =>
                {
                    b.HasOne("KnjiznicaAPI.Models.AutorKnjige", "AutorKnjige")
                        .WithMany()
                        .HasForeignKey("AutorKnjigeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorKnjige");
                });
#pragma warning restore 612, 618
        }
    }
}
